name = "ai-cafe"
main = "pages/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"
[site]
bucket = "./out"

[vars]
NEXT_PUBLIC_SUPABASE_URL = "https://vfyqhpgrsfupsahmyzuf.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZmeXFocGdyc2Z1cHNhaG15enVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA4MDI3ODksImV4cCI6MjA1NjM3ODc4OX0.PpfL4Us0BURl5vr6xdlAlvacTR-vp0JRPnE0_07SJBw"
SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZmeXFocGdyc2Z1cHNhaG15enVmIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0MDgwMjc4OSwiZXhwIjoyMDU2Mzc4Nzg5fQ.p6H6N3jhkzNgtO8Ynl73RyiVF_UJrm1uKlazYwwKFsw"
